[tool.poetry]
name = "aython"
version = "0.1.0"
description = "A Warp-like Python command palette built with Textual"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "aython", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
textual = "^0.52.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
black = "^24.0.0"
isort = "^5.13.0"
textual-dev = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
aython = "aython:run"
